version : '3'
services :
    db:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secret
        ports:
            - "27017:27017"
    api:
        build:
            context : .
            dockerfile: Dockerfile
        ports:
            - "5200:5200"
        depends_on:
            - db
        container_name : catalog_api
